# Generated by Django 5.2.6 on 2025-09-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('participant', '0002_team_remove_competitionregistration_team_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrystatus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_status', to='participant.team'),
        ),
        migrations.AddField(
            model_name='entrystatus',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.volunteer'),
        ),
        migrations.AddField(
            model_name='giftstatus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_status', to='participant.team'),
        ),
        migrations.AddField(
            model_name='giftstatus',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.volunteer'),
        ),
        migrations.AlterField(
            model_name='entrystatus',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_status', to='participant.participant'),
        ),
        migrations.AlterField(
            model_name='giftstatus',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_status', to='participant.participant'),
        ),
    ]
