# Generated by Django 5.2.6 on 2025-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_entrystatus_datetime_alter_giftstatus_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrystatus',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='giftstatus',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='v_name',
            field=models.CharField(max_length=100),
        ),
    ]
