# Generated by Django 5.2.6 on 2025-10-04 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_entrystatus_datetime_alter_giftstatus_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='api.role'),
        ),
    ]
