# Generated by Django 5.2.6 on 2025-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition_name',
            new_name='competition',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_type',
        ),
    ]
