# Generated by Django 5.2.6 on 2025-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_teamcompetition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teamcompetition',
            name='competition',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
