# Generated by Django 5.2.6 on 2025-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_competition_competition_alter_gift_gift_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teamcompetition',
            name='competition',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
