# Generated by Django 5.2.6 on 2025-10-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_competition_competition_alter_gift_gift_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamcompetition',
            name='code',
            field=models.CharField(db_index=True, default='1', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teamcompetition',
            name='competition',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
