# Generated by Django 5.2.6 on 2025-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_competition_code_segment_code_teamcompetition_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount', models.FloatField(default=10.0)),
                ('coupon_number', models.IntegerField(default=10)),
            ],
        ),
    ]
