# Generated by Django 5.2.6 on 2025-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_number',
            field=models.IntegerField(blank=True, db_index=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.FloatField(blank=True, db_index=True, default=10.0, null=True),
        ),
    ]
