# Generated by Django 5.2.6 on 2025-09-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_teamcompetition_and_more'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('payment_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='competitionregistration',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='competitionregistration',
            name='team_name',
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='participant.participant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='participant.team'),
        ),
        migrations.CreateModel(
            name='TeamCompetitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_competitions', to='event.teamcompetition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_competition_registrations', to='participant.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('institution', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=100)),
                ('is_leader', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='participant.team')),
            ],
        ),
    ]
