# Generated by Django 5.2.6 on 2025-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_team_remove_competitionregistration_team_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionregistration',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='participant',
            name='f_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='l_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='payment_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teamcompetitionregistration',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='f_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='is_leader',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='l_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
