# Generated by Django 5.2.6 on 2025-10-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_participant_campus_ambassador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
