# Generated by Django 5.2.6 on 2025-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_alter_payment_trx_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='campus_ambassador',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='club_reference',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='institution_id',
        ),
        migrations.RemoveField(
            model_name='teamparticipant',
            name='campus_ambassador',
        ),
        migrations.RemoveField(
            model_name='teamparticipant',
            name='club_reference',
        ),
        migrations.RemoveField(
            model_name='teamparticipant',
            name='institution_id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
