# Generated by Django 5.2.6 on 2025-10-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_coupons_coupon_code_and_more'),
        ('participant', '0008_remove_participant_campus_ambassador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.coupons'),
        ),
    ]
