# Generated by Django 5.2.6 on 2025-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0009_payment_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
