# Generated by Django 5.2.6 on 2025-10-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0010_participant_guardian_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
